;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cljr-slash
	dabbrev-expand
	electric-newline-and-maybe-indent
	indent-for-tab-command
	iy-go-to-char--command
	js2r-expand-node-at-point
	kill-region
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-self-insert-command
	rjsx-delete-creates-full-tag
	rjsx-electric-gt
	rjsx-electric-lt
	sp-backward-delete-char
	sp-backward-kill-word
	sp-backward-unwrap-sexp
	sp-delete-char
	sp-kill-hybrid-sexp
	sp-kill-region
	sp-kill-word
	sp-remove-active-pair-overlay
	))

(setq mc/cmds-to-run-once
      '(
	))
